name: Bug Report
description: Report a bug or issue
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
  - type: input
    id: url
    attributes:
      label: Page URL
      placeholder: https://betterbacolod.org/...
