name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like?
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
      placeholder: How would this help users?
